import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-[#E6DCCF]/20 ">
              <div className="w-full bg-[#1A3B47] py-8 top-0 z-10">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    </div>
  </div>
      <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg overflow-hidden mt-4 mb-4">
        <div className="p-8 sm:p-12">
          <h1 className="text-3xl sm:text-4xl font-bold text-[#388A94] mb-6">Privacy Policy</h1>
          <p className="text-[#1A3B47] mb-4">Last updated: November 04, 2024</p>
          <p className="text-[#1A3B47] mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p className="text-[#1A3B47] mb-8">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-[#388A94] hover:underline">Privacy Policy Generator</a>.</p>
          
          <h2 className="text-2xl font-semibold text-[#5D9297] mt-8 mb-4">Interpretation and Definitions</h2>
          <h3 className="text-xl font-semibold text-[#388A94] mt-6 mb-3">Interpretation</h3>
          <p className="text-[#1A3B47] mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          
          <h3 className="text-xl font-semibold text-[#388A94] mt-6 mb-3">Definitions</h3>
          <p className="text-[#1A3B47] mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-[#1A3B47]">
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to TripGenie.
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              <strong>Country</strong> refers to: Egypt
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>Website</strong> refers to TripGenie, accessible from <a href="www.tripgenie.com" rel="external nofollow noopener" target="_blank" className="text-[#388A94] hover:underline">www.tripgenie.com</a>
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2 className="text-2xl font-semibold text-[#5D9297] mt-8 mb-4">Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-semibold text-[#388A94] mt-6 mb-3">Types of Data Collected</h3>
          <h4 className="text-lg font-semibold text-[#5D9297] mt-4 mb-2">Personal Data</h4>
          <p className="text-[#1A3B47] mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-[#1A3B47]">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-semibold text-[#5D9297] mt-4 mb-2">Usage Data</h4>
          <p className="text-[#1A3B47] mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="text-[#1A3B47] mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className="text-[#1A3B47] mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <p className="text-[#1A3B47] mb-4">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

          {/* Continue with the rest of the privacy policy content in a similar structure */}

          <h2 className="text-2xl font-semibold text-[#5D9297] mt-8 mb-4">Contact Us</h2>
          <p className="text-[#1A3B47] mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2 text-[#1A3B47]">
            <li>By email: TripGenie@mail.com</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;